CREATE DATABASE IF NOT EXISTS student_management;
USE student_management;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  identifier VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  role ENUM('student', 'faculty', 'admin') NOT NULL,
  department VARCHAR(120) NULL,
  phone VARCHAR(30) NULL,
  registration_no VARCHAR(80) NULL,
  semester VARCHAR(20) NULL,
  section VARCHAR(20) NULL,
  batch_year VARCHAR(10) NULL,
  date_of_birth DATE NULL,
  guardian_name VARCHAR(120) NULL,
  guardian_phone VARCHAR(30) NULL,
  address VARCHAR(255) NULL,
  employee_id VARCHAR(80) NULL,
  designation VARCHAR(120) NULL,
  specialization VARCHAR(120) NULL,
  qualification VARCHAR(160) NULL,
  office_location VARCHAR(120) NULL,
  office_hours VARCHAR(120) NULL,
  joining_date DATE NULL,
  bio TEXT NULL,
  access_level VARCHAR(80) NULL,
  permissions_json JSON NULL,
  emergency_contact VARCHAR(30) NULL,
  two_factor_enabled TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  must_reset_password TINYINT(1) NOT NULL DEFAULT 0,
  photo_url VARCHAR(255) NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS registration_no VARCHAR(80) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS semester VARCHAR(20) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS section VARCHAR(20) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS batch_year VARCHAR(10) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth DATE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS guardian_name VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS guardian_phone VARCHAR(30) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS employee_id VARCHAR(80) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS designation VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS specialization VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS qualification VARCHAR(160) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS office_location VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS office_hours VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS joining_date DATE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_level VARCHAR(80) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS permissions_json JSON NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(30) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS two_factor_enabled TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS must_reset_password TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
